version: "3.9"
services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simulator-dev
    ports:
      - "5432:5432"
    volumes:
      - "pgdata_db:/var/lib/postgresql/data"
    command: ["postgres", "-c", "log_statement=all"]

  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/app

volumes:
  pgdata_db:
